name: tv-pde-inverse-problem
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26.4
  - scipy=1.13.1
  - sympy=1.13.3
  - matplotlib=3.9.2
  - mpi4py=4.0.1
  - petsc4py=3.22.2
  - pip
  - pip:
      - gurobipy==12.0.0
      - dolfinx==0.8.0
      - ufl==2024.2.0
      - black==24.10.0
      - ruff==0.9.7
      - pytest==8.3.5
